version: '3.3'
services:
  api-exchange-rate:
    image: api-exchange-rate:latest
    container_name: api-exchange-rate
    depends_on:
      - neoris-db
    ports:
      - "8080:8080"
  neoris-db:
    image: mysql:5.7
    container_name: neoris-db
    restart: always
    environment:
      MYSQL_DATABASE: 'neoris'
      MYSQL_USER: 'neoris'
      MYSQL_PASSWORD: 'neoris'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: