version: '3.3'
services:
  neoris-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'neoris'
      MYSQL_USER: 'neoris'
      MYSQL_PASSWORD: 'neoris'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: